version: "3.7"

services:
  php:
    container_name: ${MICFAULT-TOLERANCE_COMPOSE_PROJECT_NAME}_php
    user: 1000:1000
    build:
      context: .docker/php8.3-dev
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ../:/packages:rw
    working_dir: /packages/FaultTolerance

