version: "3.7"

services:
  php:
    container_name: ${MICFAULT_TOLERANCE_COMPOSE_PROJECT_NAME}_php
    user: 1000:1000
    build:
      context: .docker/php8.3-dev
    volumes:
      - ./:/app:rw
      - ~/.composer/cache/:/.composer_cache/:rw
    working_dir: /app

