<?php

declare(strict_types=1);

namespace AdgoalCommon\FaultTolerance\Tests\Unit\DataProvider\RabbitEnqueue;

use Exception;

/**
 * DataProvider for class {testClassName}.
 */
class QueueFaultTolerantRouterProcessorDataProvider
{
    /**
     * Return test data for AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantRouterProcessor.
     *
     * @return mixed[]
     */
    public function getDataForProcessMethod(): array
    {
        return [
              0 => [
                0 => [
                  'Processor' => [
                    'process' => 'delectus',
                  ],
                  'CircuitBreakerInterface' => [
                    'isAvailable' => true,
                    'isBlocked' => false,
                    'reportFailure' => null,
                    'reportSuccess' => null,
                    'getMaxFailures' => 9,
                    'getCriticalFailures' => 9,
                    'getRetryTimeout' => '05:28:34',
                    'getFailures' => 9,
                    'getLastTest' => 9,
                  ],
                  'retryTimeout' => '05:57:09',
                  'process' => 'delectus',
                  'Message' => [
                    'getBody' => 'corporis',
                    'setBody' => null,
                    'setProperties' => null,
                    'getProperties' => 'ut',
                    'setProperty' => null,
                    'getProperty' => 'ut',
                    'setHeaders' => null,
                    'getHeaders' => 'ut',
                    'setHeader' => null,
                    'getHeader' => 'ut',
                    'setRedelivered' => null,
                    'isRedelivered' => true,
                    'setCorrelationId' => null,
                    'getCorrelationId' => 'corporis',
                    'setMessageId' => null,
                    'getMessageId' => 'corporis',
                    'getTimestamp' => '10:52:09',
                    'setTimestamp' => '09:42:21',
                    'setReplyTo' => null,
                    'getReplyTo' => 'corporis',
                  ],
                  'Context' => [
                    'createMessage' => [
                      'getBody' => 'similique',
                      'setBody' => null,
                      'setProperties' => null,
                      'getProperties' => 'ipsam',
                      'setProperty' => null,
                      'getProperty' => 'ipsam',
                      'setHeaders' => null,
                      'getHeaders' => 'ipsam',
                      'setHeader' => null,
                      'getHeader' => 'ipsam',
                      'setRedelivered' => null,
                      'isRedelivered' => false,
                      'setCorrelationId' => null,
                      'getCorrelationId' => 'similique',
                      'setMessageId' => null,
                      'getMessageId' => 'similique',
                      'getTimestamp' => '13:51:18',
                      'setTimestamp' => '13:42:35',
                      'setReplyTo' => null,
                      'getReplyTo' => 'similique',
                    ],
                    'createTopic' => [
                      'getTopicName' => 'Charles Ferry',
                    ],
                    'createQueue' => [
                      'getQueueName' => 'Shanon Wunsch',
                    ],
                    'createTemporaryQueue' => [
                      'getQueueName' => 'Percy Pacocha',
                    ],
                    'createProducer' => [
                      'send' => null,
                      'getDeliveryDelay' => 1,
                      'getPriority' => 1,
                      'getTimeToLive' => '11:19:43',
                    ],
                    'createConsumer' => [
                      'getQueue' => [
                        'getQueueName' => 'Dr. Alize Wolff',
                      ],
                      'receive' => [
                        'getBody' => 'adipisci',
                        'setBody' => null,
                        'setProperties' => null,
                        'getProperties' => 'quo',
                        'setProperty' => null,
                        'getProperty' => 'quo',
                        'setHeaders' => null,
                        'getHeaders' => 'quo',
                        'setHeader' => null,
                        'getHeader' => 'quo',
                        'setRedelivered' => null,
                        'isRedelivered' => false,
                        'setCorrelationId' => null,
                        'getCorrelationId' => 'adipisci',
                        'setMessageId' => null,
                        'getMessageId' => 'adipisci',
                        'getTimestamp' => '01:47:13',
                        'setTimestamp' => '16:42:41',
                        'setReplyTo' => null,
                        'getReplyTo' => 'adipisci',
                      ],
                      'receiveNoWait' => [
                        'getBody' => 'ipsam',
                        'setBody' => null,
                        'setProperties' => null,
                        'getProperties' => 'aliquid',
                        'setProperty' => null,
                        'getProperty' => 'aliquid',
                        'setHeaders' => null,
                        'getHeaders' => 'aliquid',
                        'setHeader' => null,
                        'getHeader' => 'aliquid',
                        'setRedelivered' => null,
                        'isRedelivered' => true,
                        'setCorrelationId' => null,
                        'getCorrelationId' => 'ipsam',
                        'setMessageId' => null,
                        'getMessageId' => 'ipsam',
                        'getTimestamp' => '12:33:19',
                        'setTimestamp' => '02:43:33',
                        'setReplyTo' => null,
                        'getReplyTo' => 'ipsam',
                      ],
                      'acknowledge' => null,
                      'reject' => null,
                    ],
                    'createSubscriptionConsumer' => [
                      'consume' => null,
                      'subscribe' => null,
                      'unsubscribe' => null,
                      'unsubscribeAll' => null,
                    ],
                    'purgeQueue' => null,
                    'close' => null,
                  ],
                ],
                1 => [
                'LoggerInterface' => [
                    'warning' => 0,
                ],
                  'Processor' => [
                    'times' => 0,
                    'process' => 1,
                  ],
                  'CircuitBreakerInterface' => [
                    'times' => 0,
                    'isAvailable' => 1,
                    'isBlocked' => 0,
                    'reportFailure' => 0,
                    'reportSuccess' => 0,
                    'getMaxFailures' => 0,
                    'getCriticalFailures' => 0,
                    'getRetryTimeout' => 0,
                    'getFailures' => 0,
                    'getLastTest' => 0,
                  ],
                  'process' => 0,
                  'Message' => [
                    'times' => 0,
                    'getBody' => 0,
                    'setBody' => 0,
                    'setProperties' => 0,
                    'getProperties' => 0,
                    'setProperty' => 0,
                    'getProperty' => 0,
                    'setHeaders' => 0,
                    'getHeaders' => 0,
                    'setHeader' => 0,
                    'getHeader' => 0,
                    'setRedelivered' => 0,
                    'isRedelivered' => 0,
                    'setCorrelationId' => 0,
                    'getCorrelationId' => 0,
                    'setMessageId' => 0,
                    'getMessageId' => 0,
                    'getTimestamp' => 0,
                    'setTimestamp' => 0,
                    'setReplyTo' => 0,
                    'getReplyTo' => 0,
                  ],
                  'Context' => [
                    'times' => 0,
                    'createMessage' => [
                      'times' => 0,
                      'getBody' => 0,
                      'setBody' => 0,
                      'setProperties' => 0,
                      'getProperties' => 0,
                      'setProperty' => 0,
                      'getProperty' => 0,
                      'setHeaders' => 0,
                      'getHeaders' => 0,
                      'setHeader' => 0,
                      'getHeader' => 0,
                      'setRedelivered' => 0,
                      'isRedelivered' => 0,
                      'setCorrelationId' => 0,
                      'getCorrelationId' => 0,
                      'setMessageId' => 0,
                      'getMessageId' => 0,
                      'getTimestamp' => 0,
                      'setTimestamp' => 0,
                      'setReplyTo' => 0,
                      'getReplyTo' => 0,
                    ],
                    'createTopic' => [
                      'times' => 0,
                      'getTopicName' => 0,
                    ],
                    'createQueue' => [
                      'times' => 0,
                      'getQueueName' => 0,
                    ],
                    'createTemporaryQueue' => [
                      'times' => 0,
                      'getQueueName' => 0,
                    ],
                    'createProducer' => [
                      'times' => 0,
                      'send' => 0,
                      'getDeliveryDelay' => 0,
                      'getPriority' => 0,
                      'getTimeToLive' => 0,
                    ],
                    'createConsumer' => [
                      'times' => 0,
                      'getQueue' => [
                        'times' => 0,
                        'getQueueName' => 0,
                      ],
                      'receive' => [
                        'times' => 0,
                        'getBody' => 0,
                        'setBody' => 0,
                        'setProperties' => 0,
                        'getProperties' => 0,
                        'setProperty' => 0,
                        'getProperty' => 0,
                        'setHeaders' => 0,
                        'getHeaders' => 0,
                        'setHeader' => 0,
                        'getHeader' => 0,
                        'setRedelivered' => 0,
                        'isRedelivered' => 0,
                        'setCorrelationId' => 0,
                        'getCorrelationId' => 0,
                        'setMessageId' => 0,
                        'getMessageId' => 0,
                        'getTimestamp' => 0,
                        'setTimestamp' => 0,
                        'setReplyTo' => 0,
                        'getReplyTo' => 0,
                      ],
                      'receiveNoWait' => [
                        'times' => 0,
                        'getBody' => 0,
                        'setBody' => 0,
                        'setProperties' => 0,
                        'getProperties' => 0,
                        'setProperty' => 0,
                        'getProperty' => 0,
                        'setHeaders' => 0,
                        'getHeaders' => 0,
                        'setHeader' => 0,
                        'getHeader' => 0,
                        'setRedelivered' => 0,
                        'isRedelivered' => 0,
                        'setCorrelationId' => 0,
                        'getCorrelationId' => 0,
                        'setMessageId' => 0,
                        'getMessageId' => 0,
                        'getTimestamp' => 0,
                        'setTimestamp' => 0,
                        'setReplyTo' => 0,
                        'getReplyTo' => 0,
                      ],
                      'acknowledge' => 0,
                      'reject' => 0,
                    ],
                    'createSubscriptionConsumer' => [
                      'times' => 0,
                      'consume' => 0,
                      'subscribe' => 0,
                      'unsubscribe' => 0,
                      'unsubscribeAll' => 0,
                    ],
                    'purgeQueue' => 0,
                    'close' => 0,
                  ],
                ],
              ],
            ];
    }

    /**
     * Return test data for AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantRouterProcessor.
     *
     * @return mixed[]
     */
    public function getDataForSendEventIsAvailableFalseMethod(): array
    {
        return [
            0 => [
                0 => [
                    'Processor' => [
                        'process' => 'delectus',
                    ],
                    'CircuitBreakerInterface' => [
                        'isAvailable' => [false, false, true],
                        'isBlocked' => [false, false],
                        'reportFailure' => null,
                        'reportSuccess' => null,
                        'getMaxFailures' => 9,
                        'getCriticalFailures' => 9,
                        'getRetryTimeout' => '05:28:34',
                        'getFailures' => 9,
                        'getLastTest' => 9,
                    ],
                    'retryTimeout' => '05:57:09',
                    'process' => 'delectus',
                    'Message' => [
                        'getBody' => 'corporis',
                        'setBody' => null,
                        'setProperties' => null,
                        'getProperties' => 'ut',
                        'setProperty' => null,
                        'getProperty' => 'ut',
                        'setHeaders' => null,
                        'getHeaders' => 'ut',
                        'setHeader' => null,
                        'getHeader' => 'ut',
                        'setRedelivered' => null,
                        'isRedelivered' => true,
                        'setCorrelationId' => null,
                        'getCorrelationId' => 'corporis',
                        'setMessageId' => null,
                        'getMessageId' => 'corporis',
                        'getTimestamp' => '10:52:09',
                        'setTimestamp' => '09:42:21',
                        'setReplyTo' => null,
                        'getReplyTo' => 'corporis',
                    ],
                    'Context' => [
                        'createMessage' => [
                            'getBody' => 'similique',
                            'setBody' => null,
                            'setProperties' => null,
                            'getProperties' => 'ipsam',
                            'setProperty' => null,
                            'getProperty' => 'ipsam',
                            'setHeaders' => null,
                            'getHeaders' => 'ipsam',
                            'setHeader' => null,
                            'getHeader' => 'ipsam',
                            'setRedelivered' => null,
                            'isRedelivered' => false,
                            'setCorrelationId' => null,
                            'getCorrelationId' => 'similique',
                            'setMessageId' => null,
                            'getMessageId' => 'similique',
                            'getTimestamp' => '13:51:18',
                            'setTimestamp' => '13:42:35',
                            'setReplyTo' => null,
                            'getReplyTo' => 'similique',
                        ],
                        'createTopic' => [
                            'getTopicName' => 'Charles Ferry',
                        ],
                        'createQueue' => [
                            'getQueueName' => 'Shanon Wunsch',
                        ],
                        'createTemporaryQueue' => [
                            'getQueueName' => 'Percy Pacocha',
                        ],
                        'createProducer' => [
                            'send' => null,
                            'getDeliveryDelay' => 1,
                            'getPriority' => 1,
                            'getTimeToLive' => '11:19:43',
                        ],
                        'createConsumer' => [
                            'getQueue' => [
                                'getQueueName' => 'Dr. Alize Wolff',
                            ],
                            'receive' => [
                                'getBody' => 'adipisci',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'quo',
                                'setProperty' => null,
                                'getProperty' => 'quo',
                                'setHeaders' => null,
                                'getHeaders' => 'quo',
                                'setHeader' => null,
                                'getHeader' => 'quo',
                                'setRedelivered' => null,
                                'isRedelivered' => false,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'adipisci',
                                'setMessageId' => null,
                                'getMessageId' => 'adipisci',
                                'getTimestamp' => '01:47:13',
                                'setTimestamp' => '16:42:41',
                                'setReplyTo' => null,
                                'getReplyTo' => 'adipisci',
                            ],
                            'receiveNoWait' => [
                                'getBody' => 'ipsam',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'aliquid',
                                'setProperty' => null,
                                'getProperty' => 'aliquid',
                                'setHeaders' => null,
                                'getHeaders' => 'aliquid',
                                'setHeader' => null,
                                'getHeader' => 'aliquid',
                                'setRedelivered' => null,
                                'isRedelivered' => true,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'ipsam',
                                'setMessageId' => null,
                                'getMessageId' => 'ipsam',
                                'getTimestamp' => '12:33:19',
                                'setTimestamp' => '02:43:33',
                                'setReplyTo' => null,
                                'getReplyTo' => 'ipsam',
                            ],
                            'acknowledge' => null,
                            'reject' => null,
                        ],
                        'createSubscriptionConsumer' => [
                            'consume' => null,
                            'subscribe' => null,
                            'unsubscribe' => null,
                            'unsubscribeAll' => null,
                        ],
                        'purgeQueue' => null,
                        'close' => null,
                    ],
                ],
                1 => [
                    'LoggerInterface' => [
                        'warning' => 0,
                    ],
                    'Processor' => [
                        'times' => 0,
                        'process' => 1,
                    ],
                    'CircuitBreakerInterface' => [
                        'times' => 0,
                        'isAvailable' => 3,
                        'isBlocked' => 2,
                        'reportFailure' => 0,
                        'reportSuccess' => 0,
                        'getMaxFailures' => 0,
                        'getCriticalFailures' => 0,
                        'getRetryTimeout' => 0,
                        'getFailures' => 0,
                        'getLastTest' => 0,
                    ],
                    'process' => 0,
                    'Message' => [
                        'times' => 0,
                        'getBody' => 0,
                        'setBody' => 0,
                        'setProperties' => 0,
                        'getProperties' => 0,
                        'setProperty' => 0,
                        'getProperty' => 0,
                        'setHeaders' => 0,
                        'getHeaders' => 0,
                        'setHeader' => 0,
                        'getHeader' => 0,
                        'setRedelivered' => 0,
                        'isRedelivered' => 0,
                        'setCorrelationId' => 0,
                        'getCorrelationId' => 0,
                        'setMessageId' => 0,
                        'getMessageId' => 0,
                        'getTimestamp' => 0,
                        'setTimestamp' => 0,
                        'setReplyTo' => 0,
                        'getReplyTo' => 0,
                    ],
                    'Context' => [
                        'times' => 0,
                        'createMessage' => [
                            'times' => 0,
                            'getBody' => 0,
                            'setBody' => 0,
                            'setProperties' => 0,
                            'getProperties' => 0,
                            'setProperty' => 0,
                            'getProperty' => 0,
                            'setHeaders' => 0,
                            'getHeaders' => 0,
                            'setHeader' => 0,
                            'getHeader' => 0,
                            'setRedelivered' => 0,
                            'isRedelivered' => 0,
                            'setCorrelationId' => 0,
                            'getCorrelationId' => 0,
                            'setMessageId' => 0,
                            'getMessageId' => 0,
                            'getTimestamp' => 0,
                            'setTimestamp' => 0,
                            'setReplyTo' => 0,
                            'getReplyTo' => 0,
                        ],
                        'createTopic' => [
                            'times' => 0,
                            'getTopicName' => 0,
                        ],
                        'createQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createTemporaryQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createProducer' => [
                            'times' => 0,
                            'send' => 0,
                            'getDeliveryDelay' => 0,
                            'getPriority' => 0,
                            'getTimeToLive' => 0,
                        ],
                        'createConsumer' => [
                            'times' => 0,
                            'getQueue' => [
                                'times' => 0,
                                'getQueueName' => 0,
                            ],
                            'receive' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'receiveNoWait' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'acknowledge' => 0,
                            'reject' => 0,
                        ],
                        'createSubscriptionConsumer' => [
                            'times' => 0,
                            'consume' => 0,
                            'subscribe' => 0,
                            'unsubscribe' => 0,
                            'unsubscribeAll' => 0,
                        ],
                        'purgeQueue' => 0,
                        'close' => 0,
                    ],
                ],
            ],
        ];
    }

    /**
     * Return test data for AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantRouterProcessor.
     *
     * @return mixed[]
     */
    public function getDataForSendEventIsAvailableFalseIsBlockedTrueMethod(): array
    {
        return [
            0 => [
                0 => [
                    'Processor' => [
                        'process' => 'delectus',
                    ],
                    'CircuitBreakerInterface' => [
                        'isAvailable' => [false, false, false],
                        'isBlocked' => [false, false, true],
                        'reportFailure' => null,
                        'reportSuccess' => null,
                        'getMaxFailures' => 9,
                        'getCriticalFailures' => 9,
                        'getRetryTimeout' => '05:28:34',
                        'getFailures' => 9,
                        'getLastTest' => 9,
                    ],
                    'retryTimeout' => '05:57:09',
                    'process' => 'delectus',
                    'Message' => [
                        'getBody' => 'corporis',
                        'setBody' => null,
                        'setProperties' => null,
                        'getProperties' => 'ut',
                        'setProperty' => null,
                        'getProperty' => 'ut',
                        'setHeaders' => null,
                        'getHeaders' => 'ut',
                        'setHeader' => null,
                        'getHeader' => 'ut',
                        'setRedelivered' => null,
                        'isRedelivered' => true,
                        'setCorrelationId' => null,
                        'getCorrelationId' => 'corporis',
                        'setMessageId' => null,
                        'getMessageId' => 'corporis',
                        'getTimestamp' => '10:52:09',
                        'setTimestamp' => '09:42:21',
                        'setReplyTo' => null,
                        'getReplyTo' => 'corporis',
                    ],
                    'Context' => [
                        'createMessage' => [
                            'getBody' => 'similique',
                            'setBody' => null,
                            'setProperties' => null,
                            'getProperties' => 'ipsam',
                            'setProperty' => null,
                            'getProperty' => 'ipsam',
                            'setHeaders' => null,
                            'getHeaders' => 'ipsam',
                            'setHeader' => null,
                            'getHeader' => 'ipsam',
                            'setRedelivered' => null,
                            'isRedelivered' => false,
                            'setCorrelationId' => null,
                            'getCorrelationId' => 'similique',
                            'setMessageId' => null,
                            'getMessageId' => 'similique',
                            'getTimestamp' => '13:51:18',
                            'setTimestamp' => '13:42:35',
                            'setReplyTo' => null,
                            'getReplyTo' => 'similique',
                        ],
                        'createTopic' => [
                            'getTopicName' => 'Charles Ferry',
                        ],
                        'createQueue' => [
                            'getQueueName' => 'Shanon Wunsch',
                        ],
                        'createTemporaryQueue' => [
                            'getQueueName' => 'Percy Pacocha',
                        ],
                        'createProducer' => [
                            'send' => null,
                            'getDeliveryDelay' => 1,
                            'getPriority' => 1,
                            'getTimeToLive' => '11:19:43',
                        ],
                        'createConsumer' => [
                            'getQueue' => [
                                'getQueueName' => 'Dr. Alize Wolff',
                            ],
                            'receive' => [
                                'getBody' => 'adipisci',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'quo',
                                'setProperty' => null,
                                'getProperty' => 'quo',
                                'setHeaders' => null,
                                'getHeaders' => 'quo',
                                'setHeader' => null,
                                'getHeader' => 'quo',
                                'setRedelivered' => null,
                                'isRedelivered' => false,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'adipisci',
                                'setMessageId' => null,
                                'getMessageId' => 'adipisci',
                                'getTimestamp' => '01:47:13',
                                'setTimestamp' => '16:42:41',
                                'setReplyTo' => null,
                                'getReplyTo' => 'adipisci',
                            ],
                            'receiveNoWait' => [
                                'getBody' => 'ipsam',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'aliquid',
                                'setProperty' => null,
                                'getProperty' => 'aliquid',
                                'setHeaders' => null,
                                'getHeaders' => 'aliquid',
                                'setHeader' => null,
                                'getHeader' => 'aliquid',
                                'setRedelivered' => null,
                                'isRedelivered' => true,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'ipsam',
                                'setMessageId' => null,
                                'getMessageId' => 'ipsam',
                                'getTimestamp' => '12:33:19',
                                'setTimestamp' => '02:43:33',
                                'setReplyTo' => null,
                                'getReplyTo' => 'ipsam',
                            ],
                            'acknowledge' => null,
                            'reject' => null,
                        ],
                        'createSubscriptionConsumer' => [
                            'consume' => null,
                            'subscribe' => null,
                            'unsubscribe' => null,
                            'unsubscribeAll' => null,
                        ],
                        'purgeQueue' => null,
                        'close' => null,
                    ],
                ],
                1 => [
                    'LoggerInterface' => [
                        'warning' => 0,
                    ],
                    'Processor' => [
                        'times' => 0,
                        'process' => 0,
                    ],
                    'CircuitBreakerInterface' => [
                        'times' => 0,
                        'isAvailable' => 3,
                        'isBlocked' => 3,
                        'reportFailure' => 0,
                        'reportSuccess' => 0,
                        'getMaxFailures' => 0,
                        'getCriticalFailures' => 0,
                        'getRetryTimeout' => 0,
                        'getFailures' => 0,
                        'getLastTest' => 0,
                    ],
                    'process' => 0,
                    'Message' => [
                        'times' => 0,
                        'getBody' => 0,
                        'setBody' => 0,
                        'setProperties' => 0,
                        'getProperties' => 0,
                        'setProperty' => 0,
                        'getProperty' => 0,
                        'setHeaders' => 0,
                        'getHeaders' => 0,
                        'setHeader' => 0,
                        'getHeader' => 0,
                        'setRedelivered' => 0,
                        'isRedelivered' => 0,
                        'setCorrelationId' => 0,
                        'getCorrelationId' => 0,
                        'setMessageId' => 0,
                        'getMessageId' => 0,
                        'getTimestamp' => 0,
                        'setTimestamp' => 0,
                        'setReplyTo' => 0,
                        'getReplyTo' => 0,
                    ],
                    'Context' => [
                        'times' => 0,
                        'createMessage' => [
                            'times' => 0,
                            'getBody' => 0,
                            'setBody' => 0,
                            'setProperties' => 0,
                            'getProperties' => 0,
                            'setProperty' => 0,
                            'getProperty' => 0,
                            'setHeaders' => 0,
                            'getHeaders' => 0,
                            'setHeader' => 0,
                            'getHeader' => 0,
                            'setRedelivered' => 0,
                            'isRedelivered' => 0,
                            'setCorrelationId' => 0,
                            'getCorrelationId' => 0,
                            'setMessageId' => 0,
                            'getMessageId' => 0,
                            'getTimestamp' => 0,
                            'setTimestamp' => 0,
                            'setReplyTo' => 0,
                            'getReplyTo' => 0,
                        ],
                        'createTopic' => [
                            'times' => 0,
                            'getTopicName' => 0,
                        ],
                        'createQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createTemporaryQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createProducer' => [
                            'times' => 0,
                            'send' => 0,
                            'getDeliveryDelay' => 0,
                            'getPriority' => 0,
                            'getTimeToLive' => 0,
                        ],
                        'createConsumer' => [
                            'times' => 0,
                            'getQueue' => [
                                'times' => 0,
                                'getQueueName' => 0,
                            ],
                            'receive' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'receiveNoWait' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'acknowledge' => 0,
                            'reject' => 0,
                        ],
                        'createSubscriptionConsumer' => [
                            'times' => 0,
                            'consume' => 0,
                            'subscribe' => 0,
                            'unsubscribe' => 0,
                            'unsubscribeAll' => 0,
                        ],
                        'purgeQueue' => 0,
                        'close' => 0,
                    ],
                ],
            ],
        ];
    }

    /**
     * Return test data for AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantRouterProcessor.
     *
     * @return mixed[]
     */
    public function getDataForSendEventIsAvailableFalseIsBlockedTrueWithExceptionMethod(): array
    {
        return [
            0 => [
                0 => [
                    'Processor' => [
                        'process' => [
                            'exception' => Exception::class,
                        ],
                    ],
                    'CircuitBreakerInterface' => [
                        'isAvailable' => [true, true, false],
                        'isBlocked' => [false, true],
                        'reportFailure' => null,
                        'reportSuccess' => null,
                        'getMaxFailures' => 9,
                        'getCriticalFailures' => 9,
                        'getRetryTimeout' => '05:28:34',
                        'getFailures' => 9,
                        'getLastTest' => 9,
                    ],
                    'retryTimeout' => '05:57:09',
                    'process' => 'delectus',
                    'Message' => [
                        'getBody' => 'corporis',
                        'setBody' => null,
                        'setProperties' => null,
                        'getProperties' => 'ut',
                        'setProperty' => null,
                        'getProperty' => 'ut',
                        'setHeaders' => null,
                        'getHeaders' => 'ut',
                        'setHeader' => null,
                        'getHeader' => 'ut',
                        'setRedelivered' => null,
                        'isRedelivered' => true,
                        'setCorrelationId' => null,
                        'getCorrelationId' => 'corporis',
                        'setMessageId' => null,
                        'getMessageId' => 'corporis',
                        'getTimestamp' => '10:52:09',
                        'setTimestamp' => '09:42:21',
                        'setReplyTo' => null,
                        'getReplyTo' => 'corporis',
                    ],
                    'Context' => [
                        'createMessage' => [
                            'getBody' => 'similique',
                            'setBody' => null,
                            'setProperties' => null,
                            'getProperties' => 'ipsam',
                            'setProperty' => null,
                            'getProperty' => 'ipsam',
                            'setHeaders' => null,
                            'getHeaders' => 'ipsam',
                            'setHeader' => null,
                            'getHeader' => 'ipsam',
                            'setRedelivered' => null,
                            'isRedelivered' => false,
                            'setCorrelationId' => null,
                            'getCorrelationId' => 'similique',
                            'setMessageId' => null,
                            'getMessageId' => 'similique',
                            'getTimestamp' => '13:51:18',
                            'setTimestamp' => '13:42:35',
                            'setReplyTo' => null,
                            'getReplyTo' => 'similique',
                        ],
                        'createTopic' => [
                            'getTopicName' => 'Charles Ferry',
                        ],
                        'createQueue' => [
                            'getQueueName' => 'Shanon Wunsch',
                        ],
                        'createTemporaryQueue' => [
                            'getQueueName' => 'Percy Pacocha',
                        ],
                        'createProducer' => [
                            'send' => null,
                            'getDeliveryDelay' => 1,
                            'getPriority' => 1,
                            'getTimeToLive' => '11:19:43',
                        ],
                        'createConsumer' => [
                            'getQueue' => [
                                'getQueueName' => 'Dr. Alize Wolff',
                            ],
                            'receive' => [
                                'getBody' => 'adipisci',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'quo',
                                'setProperty' => null,
                                'getProperty' => 'quo',
                                'setHeaders' => null,
                                'getHeaders' => 'quo',
                                'setHeader' => null,
                                'getHeader' => 'quo',
                                'setRedelivered' => null,
                                'isRedelivered' => false,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'adipisci',
                                'setMessageId' => null,
                                'getMessageId' => 'adipisci',
                                'getTimestamp' => '01:47:13',
                                'setTimestamp' => '16:42:41',
                                'setReplyTo' => null,
                                'getReplyTo' => 'adipisci',
                            ],
                            'receiveNoWait' => [
                                'getBody' => 'ipsam',
                                'setBody' => null,
                                'setProperties' => null,
                                'getProperties' => 'aliquid',
                                'setProperty' => null,
                                'getProperty' => 'aliquid',
                                'setHeaders' => null,
                                'getHeaders' => 'aliquid',
                                'setHeader' => null,
                                'getHeader' => 'aliquid',
                                'setRedelivered' => null,
                                'isRedelivered' => true,
                                'setCorrelationId' => null,
                                'getCorrelationId' => 'ipsam',
                                'setMessageId' => null,
                                'getMessageId' => 'ipsam',
                                'getTimestamp' => '12:33:19',
                                'setTimestamp' => '02:43:33',
                                'setReplyTo' => null,
                                'getReplyTo' => 'ipsam',
                            ],
                            'acknowledge' => null,
                            'reject' => null,
                        ],
                        'createSubscriptionConsumer' => [
                            'consume' => null,
                            'subscribe' => null,
                            'unsubscribe' => null,
                            'unsubscribeAll' => null,
                        ],
                        'purgeQueue' => null,
                        'close' => null,
                    ],
                ],
                1 => [
                    'LoggerInterface' => [
                        'warning' => 1,
                    ],
                    'Processor' => [
                        'times' => 0,
                        'process' => 1,
                    ],
                    'CircuitBreakerInterface' => [
                        'times' => 0,
                        'isAvailable' => 4,
                        'isBlocked' => 2,
                        'reportFailure' => 2,
                        'reportSuccess' => 0,
                        'getMaxFailures' => 0,
                        'getCriticalFailures' => 0,
                        'getRetryTimeout' => 0,
                        'getFailures' => 0,
                        'getLastTest' => 0,
                    ],
                    'process' => 0,
                    'Message' => [
                        'times' => 0,
                        'getBody' => 0,
                        'setBody' => 0,
                        'setProperties' => 0,
                        'getProperties' => 0,
                        'setProperty' => 0,
                        'getProperty' => 0,
                        'setHeaders' => 0,
                        'getHeaders' => 0,
                        'setHeader' => 0,
                        'getHeader' => 0,
                        'setRedelivered' => 0,
                        'isRedelivered' => 0,
                        'setCorrelationId' => 0,
                        'getCorrelationId' => 0,
                        'setMessageId' => 0,
                        'getMessageId' => 0,
                        'getTimestamp' => 0,
                        'setTimestamp' => 0,
                        'setReplyTo' => 0,
                        'getReplyTo' => 0,
                    ],
                    'Context' => [
                        'times' => 0,
                        'createMessage' => [
                            'times' => 0,
                            'getBody' => 0,
                            'setBody' => 0,
                            'setProperties' => 0,
                            'getProperties' => 0,
                            'setProperty' => 0,
                            'getProperty' => 0,
                            'setHeaders' => 0,
                            'getHeaders' => 0,
                            'setHeader' => 0,
                            'getHeader' => 0,
                            'setRedelivered' => 0,
                            'isRedelivered' => 0,
                            'setCorrelationId' => 0,
                            'getCorrelationId' => 0,
                            'setMessageId' => 0,
                            'getMessageId' => 0,
                            'getTimestamp' => 0,
                            'setTimestamp' => 0,
                            'setReplyTo' => 0,
                            'getReplyTo' => 0,
                        ],
                        'createTopic' => [
                            'times' => 0,
                            'getTopicName' => 0,
                        ],
                        'createQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createTemporaryQueue' => [
                            'times' => 0,
                            'getQueueName' => 0,
                        ],
                        'createProducer' => [
                            'times' => 0,
                            'send' => 0,
                            'getDeliveryDelay' => 0,
                            'getPriority' => 0,
                            'getTimeToLive' => 0,
                        ],
                        'createConsumer' => [
                            'times' => 0,
                            'getQueue' => [
                                'times' => 0,
                                'getQueueName' => 0,
                            ],
                            'receive' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'receiveNoWait' => [
                                'times' => 0,
                                'getBody' => 0,
                                'setBody' => 0,
                                'setProperties' => 0,
                                'getProperties' => 0,
                                'setProperty' => 0,
                                'getProperty' => 0,
                                'setHeaders' => 0,
                                'getHeaders' => 0,
                                'setHeader' => 0,
                                'getHeader' => 0,
                                'setRedelivered' => 0,
                                'isRedelivered' => 0,
                                'setCorrelationId' => 0,
                                'getCorrelationId' => 0,
                                'setMessageId' => 0,
                                'getMessageId' => 0,
                                'getTimestamp' => 0,
                                'setTimestamp' => 0,
                                'setReplyTo' => 0,
                                'getReplyTo' => 0,
                            ],
                            'acknowledge' => 0,
                            'reject' => 0,
                        ],
                        'createSubscriptionConsumer' => [
                            'times' => 0,
                            'consume' => 0,
                            'subscribe' => 0,
                            'unsubscribe' => 0,
                            'unsubscribeAll' => 0,
                        ],
                        'purgeQueue' => 0,
                        'close' => 0,
                    ],
                ],
            ],
        ];
    }
}
